/* eslint-disable */
//
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "use-boolean": {
    name: "use-boolean",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-boolean.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-boolean.tsx")),
    source: "",
  },
  "use-toggle": {
    name: "use-toggle",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-toggle.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-toggle.tsx")),
    source: "",
  },
  "use-copy-to-clipboard": {
    name: "use-copy-to-clipboard",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-copy-to-clipboard.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-copy-to-clipboard-demo")
    ),
    source: "",
  },
  "use-unmount": {
    name: "use-unmount",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-unmount.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-unmount.tsx")),
    source: "",
  },
  "use-debounce-callback": {
    name: "use-debounce-callback",
    type: "registry:hook",
    registryDependencies: ["https://usekit.kiron.dev/r/use-unmount"],
    files: [
      {
        path: "registry/hooks/use-debounce-callback.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-debounce-callback.tsx")
    ),
    source: "",
  },
  "use-isomorphic-layout-effect": {
    name: "use-isomorphic-layout-effect",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-isomorphic-layout-effect.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-isomorphic-layout-effect.tsx")
    ),
    source: "",
  },
  "use-interval": {
    name: "use-interval",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-interval.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-interval-demo")),
    source: "",
  },
  "use-timeout": {
    name: "use-timeout",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-timeout.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-timeout-demo")),
    source: "",
  },
  "use-document-title": {
    name: "use-document-title",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-document-title.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-document-title-demo")
    ),
    source: "",
  },
  "use-counter": {
    name: "use-counter",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-counter.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-counter-demo")),
    source: "",
  },
  "use-mouse-position": {
    name: "use-mouse-position",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-mouse-position.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-mouse-position-demo")
    ),
    source: "",
  },
  "use-battery": {
    name: "use-battery",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-battery.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-battery-demo")),
    source: "",
  },
  "use-local-storage": {
    name: "use-local-storage",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-local-storage.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-local-storage-demo")
    ),
    source: "",
  },
  "use-session-storage": {
    name: "use-session-storage",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-session-storage.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-session-storage-demo")
    ),
    source: "",
  },
  "use-fetch": {
    name: "use-fetch",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-fetch.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-fetch-demo")),
    source: "",
  },
  "use-script": {
    name: "use-script",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-script.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-script-demo")),
    source: "",
  },
  "use-scramble": {
    name: "use-scramble",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-scramble.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-scramble-demo")),
    source: "",
  },
  "use-intersection-observer": {
    name: "use-intersection-observer",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-intersection-observer.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-intersection-observer.tsx")
    ),
    source: "",
  },
  "use-render-count": {
    name: "use-render-count",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-render-count.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-render-count-demo")
    ),
    source: "",
  },
  "use-orientation": {
    name: "use-orientation",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-orientation.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-orientation-demo")
    ),
    source: "",
  },
  "use-window-size": {
    name: "use-window-size",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-window-size.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-window-size-demo")
    ),
    source: "",
  },
  "use-hover": {
    name: "use-hover",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-hover.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-hover-demo")),
    source: "",
  },
  "use-media-query": {
    name: "use-media-query",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-media-query.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-media-query-demo")
    ),
    source: "",
  },
  "use-interval-when": {
    name: "use-interval-when",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-interval-when.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-interval-when-demo")
    ),
    source: "",
  },
  "use-countdown": {
    name: "use-countdown",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-countdown.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-countdown-demo")),
    source: "",
  },
  "use-visibility-change": {
    name: "use-visibility-change",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-visibility-change.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-visibility-change-demo")
    ),
    source: "",
  },
  "use-key-press": {
    name: "use-key-press",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-key-press.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-key-press-demo")),
    source: "",
  },
  "use-cookie-storage": {
    name: "use-cookie-storage",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-cookie-storage.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-cookie-storage-demo")
    ),
    source: "",
  },
  "use-is-client": {
    name: "use-is-client",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-is-client.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-is-client-demo")),
    source: "",
  },
  "use-geolocation": {
    name: "use-geolocation",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-geolocation.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-geolocation-demo")
    ),
    source: "",
  },
  "use-page-leave": {
    name: "use-page-leave",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-page-leave.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-page-leave-demo")
    ),
    source: "",
  },
  "use-is-first-render": {
    name: "use-is-first-render",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-is-first-render.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-is-first-render-demo")
    ),
    source: "",
  },
  "use-window-scroll": {
    name: "use-window-scroll",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-window-scroll.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-window-scroll-demo")
    ),
    source: "",
  },
  "use-idle": {
    name: "use-idle",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-idle.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-idle-demo")),
    source: "",
  },
  "use-long-press": {
    name: "use-long-press",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-long-press.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-long-press-demo")
    ),
    source: "",
  },
  "use-default": {
    name: "use-default",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-default.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-default-demo")),
    source: "",
  },
  "use-click-away": {
    name: "use-click-away",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-click-away.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-click-away-demo")
    ),
    source: "",
  },
  "use-object-state": {
    name: "use-object-state",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-object-state.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-object-state-demo")
    ),
    source: "",
  },
  "use-logger": {
    name: "use-logger",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-logger.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-logger-demo")),
    source: "",
  },
  "use-speakup": {
    name: "use-speakup",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-speakup.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-speakup-demo")),
    source: "",
  },
  "use-any-measure": {
    name: "use-any-measure",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-any-measure.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-any-measure-demo")
    ),
    source: "",
  },
  "use-is-mobile": {
    name: "use-is-mobile",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-is-mobile.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-is-mobile.tsx")),
    source: "",
  },
  "use-lock-body-scroll": {
    name: "use-lock-body-scroll",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-lock-body-scroll.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-lock-body-scroll.tsx")
    ),
    source: "",
  },
  "use-mounted": {
    name: "use-mounted",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-mounted.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-mounted.tsx")),
    source: "",
  },
  "use-mutation-observer": {
    name: "use-mutation-observer",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-mutation-observer.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-mutation-observer.tsx")
    ),
    source: "",
  },
  "use-previous": {
    name: "use-previous",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-previous.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-previous-demo")),
    source: "",
  },
  "use-history-state": {
    name: "use-history-state",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-history-state.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-history-state-demo")
    ),
    source: "",
  },
  "use-async-status": {
    name: "use-async-status",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-async-status.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-async-status-demo")
    ),
    source: "",
  },
  "use-favicon": {
    name: "use-favicon",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-favicon.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-favicon-demo")),
    source: "",
  },
  "use-list": {
    name: "use-list",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-list.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-list-demo")),
    source: "",
  },
  "use-map": {
    name: "use-map",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-map.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-map.tsx")),
    source: "",
  },
  "use-queue": {
    name: "use-queue",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-queue.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-queue.tsx")),
    source: "",
  },
  "use-set": {
    name: "use-set",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-set.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-set.tsx")),
    source: "",
  },
  "use-throttle": {
    name: "use-throttle",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-throttle.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-throttle.tsx")),
    source: "",
  },
  "use-continuous-retry": {
    name: "use-continuous-retry",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-continuous-retry.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-continuous-retry.tsx")
    ),
    source: "",
  },
  "use-event-listener": {
    name: "use-event-listener",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-event-listener.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-event-listener.tsx")
    ),
    source: "",
  },
  "use-random-interval": {
    name: "use-random-interval",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-random-interval.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-random-interval.tsx")
    ),
    source: "",
  },
  "use-copy-to-clipboard-demo": {
    name: "use-copy-to-clipboard-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-copy-to-clipboard-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-copy-to-clipboard-demo")
    ),
    source: "",
  },
  "use-interval-demo": {
    name: "use-interval-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-interval-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-interval-demo")),
    source: "",
  },
  "use-timeout-demo": {
    name: "use-timeout-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-timeout-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-timeout-demo")),
    source: "",
  },
  "use-document-title-demo": {
    name: "use-document-title-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-document-title-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-document-title-demo")
    ),
    source: "",
  },
  "use-mouse-position-demo": {
    name: "use-mouse-position-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-mouse-position-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-mouse-position-demo")
    ),
    source: "",
  },
  "use-counter-demo": {
    name: "use-counter-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-counter-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-counter-demo")),
    source: "",
  },
  "use-scramble-demo": {
    name: "use-scramble-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-scramble-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-scramble-demo")),
    source: "",
  },
  "use-fetch-demo": {
    name: "use-fetch-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-fetch-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-fetch-demo")),
    source: "",
  },
  "use-local-storage-demo": {
    name: "use-local-storage-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-local-storage-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-local-storage-demo")
    ),
    source: "",
  },
  "use-session-storage-demo": {
    name: "use-session-storage-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-session-storage-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-session-storage-demo")
    ),
    source: "",
  },
  "use-script-demo": {
    name: "use-script-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-script-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-script-demo")),
    source: "",
  },
  "use-render-count-demo": {
    name: "use-render-count-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-render-count-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-render-count-demo")
    ),
    source: "",
  },
  "use-orientation-demo": {
    name: "use-orientation-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-orientation-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-orientation-demo")
    ),
    source: "",
  },
  "use-window-size-demo": {
    name: "use-window-size-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-window-size-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-window-size-demo")
    ),
    source: "",
  },
  "use-hover-demo": {
    name: "use-hover-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-hover-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-hover-demo")),
    source: "",
  },
  "use-battery-demo": {
    name: "use-battery-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-battery-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-battery-demo")),
    source: "",
  },
  "use-media-query-demo": {
    name: "use-media-query-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-media-query-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-media-query-demo")
    ),
    source: "",
  },
  "use-interval-when-demo": {
    name: "use-interval-when-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-interval-when-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-interval-when-demo")
    ),
    source: "",
  },
  "use-countdown-demo": {
    name: "use-countdown-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-countdown-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-countdown-demo")),
    source: "",
  },
  "use-visibility-change-demo": {
    name: "use-visibility-change-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-visibility-change-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-visibility-change-demo")
    ),
    source: "",
  },
  "use-key-press-demo": {
    name: "use-key-press-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-key-press-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-key-press-demo")),
    source: "",
  },
  "use-cookie-storage-demo": {
    name: "use-cookie-storage-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-cookie-storage-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-cookie-storage-demo")
    ),
    source: "",
  },
  "use-is-client-demo": {
    name: "use-is-client-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-is-client-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-is-client-demo")),
    source: "",
  },
  "use-geolocation-demo": {
    name: "use-geolocation-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-geolocation-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-geolocation-demo")
    ),
    source: "",
  },
  "use-page-leave-demo": {
    name: "use-page-leave-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-page-leave-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-page-leave-demo")
    ),
    source: "",
  },
  "use-is-first-render-demo": {
    name: "use-is-first-render-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-is-first-render-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-is-first-render-demo")
    ),
    source: "",
  },
  "use-window-scroll-demo": {
    name: "use-window-scroll-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-window-scroll-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-window-scroll-demo")
    ),
    source: "",
  },
  "use-idle-demo": {
    name: "use-idle-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-idle-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-idle-demo")),
    source: "",
  },
  "use-long-press-demo": {
    name: "use-long-press-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-long-press-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-long-press-demo")
    ),
    source: "",
  },
  "use-default-demo": {
    name: "use-default-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-default-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-default-demo")),
    source: "",
  },
  "use-click-away-demo": {
    name: "use-click-away-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-click-away-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-click-away-demo")
    ),
    source: "",
  },
  "use-object-state-demo": {
    name: "use-object-state-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-object-state-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-object-state-demo")
    ),
    source: "",
  },
  "use-logger-demo": {
    name: "use-logger-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-logger-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-logger-demo")),
    source: "",
  },
  "use-speakup-demo": {
    name: "use-speakup-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-speakup-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-speakup-demo")),
    source: "",
  },
  "use-any-measure-demo": {
    name: "use-any-measure-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-any-measure-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-any-measure-demo")
    ),
    source: "",
  },
  "use-previous-demo": {
    name: "use-previous-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-previous-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-previous-demo")),
    source: "",
  },
  "use-history-state-demo": {
    name: "use-history-state-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-history-state-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-history-state-demo")
    ),
    source: "",
  },
  "use-async-status-demo": {
    name: "use-async-status-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-async-status-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-async-status-demo")
    ),
    source: "",
  },
  "use-favicon-demo": {
    name: "use-favicon-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-favicon-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-favicon-demo")),
    source: "",
  },
  "use-list-demo": {
    name: "use-list-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-list-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-list-demo")),
    source: "",
  },
}
