/* eslint-disable */
//
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "use-boolean": {
    name: "use-boolean",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-boolean.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-boolean.tsx")),
    source: "",
  },
  "use-toggle": {
    name: "use-toggle",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-toggle.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-toggle.tsx")),
    source: "",
  },
  "use-copy-to-clipboard": {
    name: "use-copy-to-clipboard",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-copy-to-clipboard.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-copy-to-clipboard-demo")
    ),
    source: "",
  },
  "use-unmount": {
    name: "use-unmount",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-unmount.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-unmount.tsx")),
    source: "",
  },
  "use-debounce-callback": {
    name: "use-debounce-callback",
    type: "registry:hook",
    registryDependencies: ["https://usekit.kiron.dev/r/use-unmount"],
    files: [
      {
        path: "registry/hooks/use-debounce-callback.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-debounce-callback.tsx")
    ),
    source: "",
  },
  "use-isomorphic-layout-effect": {
    name: "use-isomorphic-layout-effect",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-isomorphic-layout-effect.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/hooks/use-isomorphic-layout-effect.tsx")
    ),
    source: "",
  },
  "use-interval": {
    name: "use-interval",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-interval.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-interval-demo")),
    source: "",
  },
  "use-timeout": {
    name: "use-timeout",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-timeout.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-timeout-demo")),
    source: "",
  },
  "use-document-title": {
    name: "use-document-title",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-document-title.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-document-title-demo")
    ),
    source: "",
  },
  "use-counter": {
    name: "use-counter",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-counter.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-counter-demo")),
    source: "",
  },
  "use-mouse-position": {
    name: "use-mouse-position",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-mouse-position.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-mouse-position-demo")
    ),
    source: "",
  },
  "use-battery": {
    name: "use-battery",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-battery.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/hooks/use-battery.tsx")),
    source: "",
  },
  "use-local-storage": {
    name: "use-local-storage",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-local-storage.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-local-storage-demo")
    ),
    source: "",
  },
  "use-session-storage": {
    name: "use-session-storage",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-session-storage.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-session-storage-demo")
    ),
    source: "",
  },
  "use-fetch": {
    name: "use-fetch",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-fetch.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-fetch-demo")),
    source: "",
  },
  "use-script": {
    name: "use-script",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-script.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-script-demo")),
    source: "",
  },
  "use-scramble": {
    name: "use-scramble",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-scramble.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-scramble-demo")),
    source: "",
  },
  "use-intersection-observer": {
    name: "use-intersection-observer",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-intersection-observer.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-intersection-observer-demo")
    ),
    source: "",
  },
  "use-render-count": {
    name: "use-render-count",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-render-count.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-render-count-demo")
    ),
    source: "",
  },
  "use-orientation": {
    name: "use-orientation",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/hooks/use-orientation.tsx",
        type: "registry:hook",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-orientation-demo")
    ),
    source: "",
  },
  "use-copy-to-clipboard-demo": {
    name: "use-copy-to-clipboard-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-copy-to-clipboard-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-copy-to-clipboard-demo")
    ),
    source: "",
  },
  "use-interval-demo": {
    name: "use-interval-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-interval-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-interval-demo")),
    source: "",
  },
  "use-timeout-demo": {
    name: "use-timeout-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-timeout-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-timeout-demo")),
    source: "",
  },
  "use-document-title-demo": {
    name: "use-document-title-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-document-title-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-document-title-demo")
    ),
    source: "",
  },
  "use-mouse-position-demo": {
    name: "use-mouse-position-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-mouse-position-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-mouse-position-demo")
    ),
    source: "",
  },
  "use-counter-demo": {
    name: "use-counter-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-counter-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-counter-demo")),
    source: "",
  },
  "use-scramble-demo": {
    name: "use-scramble-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-scramble-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-scramble-demo")),
    source: "",
  },
  "use-fetch-demo": {
    name: "use-fetch-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-fetch-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-fetch-demo")),
    source: "",
  },
  "use-local-storage-demo": {
    name: "use-local-storage-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-local-storage-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-local-storage-demo")
    ),
    source: "",
  },
  "use-session-storage-demo": {
    name: "use-session-storage-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-session-storage-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-session-storage-demo")
    ),
    source: "",
  },
  "use-script-demo": {
    name: "use-script-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-script-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(() => import("registry/examples/use-script-demo")),
    source: "",
  },
  "use-intersection-observer-demo": {
    name: "use-intersection-observer-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-intersection-observer-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-intersection-observer-demo")
    ),
    source: "",
  },
  "use-render-count-demo": {
    name: "use-render-count-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-render-count-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-render-count-demo")
    ),
    source: "",
  },
  "use-orientation-demo": {
    name: "use-orientation-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/examples/use-orientation-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(
      () => import("registry/examples/use-orientation-demo")
    ),
    source: "",
  },
}
